os:
- linux
language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27
licenses:
  - 'android-sdk-license-.+'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
env:
  global:
  - secure: ID13f+uiqK4oe9v7FIkHDE3EPmCF6Z1ii6EX1lC6mKWX+OXsOmHcwvx8e1eQMgV/dkdSuy0IbnMlnlcW67ZjJ8DfRjgiheVyZTdJlHFj6IlhbY84MMS1zyZjrJEC6wHJvFKUKX3GtCVGKgacAkPoBXP9u9dgoyIoct3eTDtRjvzlJOMeoWAzD1rxqnlePqaJMgif9rBdH7Q7Bt28IN5dkM7B1La+qPPv9d/LLpFk1EpLUSoX6CK9/5KYkpIAI0RDQNGuKjfv1gasE07rdG/Kti5l9S2B2Y4/jDodWdyR4QNDD/1jK6KWJ+Rm0bsRJfYe8PY4MehhQkqCK5Cp8fZi2vpgyYfc18jth2JCDO9Qqo2r+3KHceRU8p/EF1s2sghoJpiKslEZ+jTCED2aYItntzaM+hPuOZP0SNR1QwQSQGmhMBQvYe3sSsWTpmEGBknIg/5i4YCcBYKd6eWkdR0Q2j2qrirn+qFPD9vuQXGume1e0D7hom9g5Vn1bqibSGtUtIaXKFOIrK8EBBr2tqaFVOSiY99vJiAgZwfhkTYU0Tn9Q33f17mqT4e15hYRS7BnI1/Wfpd28kb57WllF/j/dvzjWaD1rRVSJOTa5U2C6G2Q4AKJkwEyrE9DDES/d6mLidhVvC6mZMjXqxcl3CVB/0YMHdDeu0UsgFRl9bjLQCE=
  - secure: TRJAHOaOzeJZETJ3Od9vHlIRw9nSkVv65gfTpWrpjcWwEOEZQkjWvz75qFcOHQ0FDz0W2xAnbKScWmSDxeSgoeyn62obe3LG9Bvn6Wx/bR871ElZP8Zdvhszw6BQqB2BamOeGSk7Gf/CeSf5DXGHHqOHRu2+4PpKiCRjL6+pEDl5GNckYhw4saF/wxjwZLT/q1vOsaodWusA340YTB8cTvOm5vqfhdgPMbIp+vllvfrJXG1SCkRCuVkgy3gg7vq067YNYAEQsIZlrPg6v+CVpNJkDJhMwVMoW7E/NTqVaRPB4sAcaO0tjL4uArbYTgTbLGWjvM/cNZX96gJe6KV2/6e8Eo0MCszxGgOzQsTWRHvAasEOYmVEcmRTfeHnvKjDHokSfdaGbg36qZT4sVQCebpYTWHuAyYHRgNdQ/TCCRAEOehePFf1KQI3aeoUX9IsfcZYQH5t7XoZRsg4vfathGdZaKbK61JlrYld0/9Cp7kdGh0Ae7RSSdfuTh/yjgvOoPaDPtCz9wlh7KoftTCxIKMgJGIhK7c7LDlYGpHJptsiKI7FBwFUsOErD4smI/kdtqNQ0gCmokIgjbHST23XUDsJuh2n94TLUnPDaUJccZWCKyBu6WbdJy+j5tCO/vZYFI4U0du0fC+/lRYcx1PzJCiDp0XIlHHSaWqsGAjn/iM=
  - secure: wFsV7S5hYV0yiuKaqSMaghY6PUcK6DWURHrsZtzdYEYkdyzzYdjviGagh4lY0zMxgSa322GUFDvBks8pXKrXi785wjFqbrObEimnRbXzIBFTYbK0enpz6HfLpSBFXSwfdKru2+HUtrIXqu1itIMRzcgwJvUB4aWfPO9lfDlcVyaGu8xr2IejXA8KqlbzqkoUwbG4tcrv11lyBNOyZXlohl+Pt1ItFmO+Nd2/qm9LbXTy61woFVW1BHF6oRFZ5oHv7siQvfuxd1L8DIsfS2kLLjGMaljYh9wn/00STCN7fk05ye4ZlppBAobOcEzr/Xm5VNBk59/pdHkrIPWXlGjhKwyDl7QOaZ+ZhHYJ2n8pm6r6K9iSX/jHnsTIIlfog+i9akYQJ38xKcBlTOIRJn7O42asRSvVMdjtyLwDqy4JD91WS6pBULAd/a1IO08HTgR7uBT+mbIw8kFLULwVpg8E0n5GcTTK0hLwW5gQETKuBa3ON7olFjMVU+ZuY/+aI3E/6prY9u7GNx5Fh1Qj4dpzrQ2vtOHzIt0nA1SPsq1phWg+81j95L8XKL2Ig7rvq0hiZXj3FJGF43RxtAwWvVh1FrDCQXL70b3T/xLjdR+vuXjl7NKqLdwESUJnSTQJMES4tX4E1Rk+WnsM3EYqYuid0//xd6rooBqCkz/3ef2DbbU=
before_script:
- "./ci/before_script"
script:
- "./ci/script"
after_script:
- rm assets/secrets.json
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  provider: releases
  api_key:
    secure: cnHHRP3xk/OAMfrR/FHXCTfnf5Zo6GJS73ha/qraqDCQNYTXP3t3r17qylSj20gK3hxGlzzlfc0pIcOl/x5amd4lKdYbpRHMsDFEpwj7C0X9lJqX2sxZqSIXxsET83Z4A+VlRNLk9fQaE4Bky5IKUhqJkVEYGHk1pk8pyQ1ldam9Q4vz6+Xcvink1yy9kOFJD3MQkn64Rw71SJiabQK69oYxjNSBA6uS3P1ZbNoD7sMSSfzz2rLHzAJrqb2h4iikFNnq+9wHhUbJW0p0h2dd42t2LTomJrp99feTyv8e7HxGFj2XO1E1BRDl0xsfKsz+Idww8fwbHsn1F2Bz+fB284P9Hm2Nl0A02RiZ4GZnOZmVutCODG/KxMyM3PKUOneVTQrb0lqsgnLddIAUMifJNN6iap5IluOU5Oso1HSttbVn9RvTOvXU9+4LDCrfQdEa6huuHIXYi1amaG/WlfDR2iSd7nxoeGaJIq0I3UPkGYHVg7kVfQMfOA+yIZ9Dg6ngvQZydJ9oxcfKfVkbmoST3keHACaGZd5O1r0O3kAC7qJutMc/fwNhHH+zlt6d9kFDeecVT3aV99iUnkYEeuDpFic0B614BkQm/QFW5/duWcJtkCWgfb+hDHKXt972mtspKcroORwUCDCdECKFyVzvutTdszP+Q/Mm1UuCx+K2kXk=
  file: build/app/outputs/apk/app.apk
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: TheNightmanCodeth/DitRa
